/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CardType {
  'id' : bigint,
  'turnaroundDays' : bigint,
  'name' : string,
  'pricePerCard' : number,
  'description' : string,
}
export interface Customer {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface DashboardStats {
  'cancelledOrders' : bigint,
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'readyOrders' : bigint,
  'inProductionOrders' : bigint,
  'totalRevenue' : number,
  'deliveredOrders' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'cardTypeId' : bigint,
  'notes' : string,
  'quantity' : bigint,
  'customerId' : bigint,
  'totalPrice' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCardType' : ActorMethod<[CardType], bigint>,
  'createCustomer' : ActorMethod<[Customer], bigint>,
  'createOrder' : ActorMethod<[Order], bigint>,
  'deleteCardType' : ActorMethod<[bigint], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'getAllCardTypes' : ActorMethod<[], Array<CardType>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCardType' : ActorMethod<[bigint], [] | [CardType]>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByCustomerId' : ActorMethod<[bigint], Array<Order>>,
  'getOrdersByStatus' : ActorMethod<[string], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCardType' : ActorMethod<[bigint, CardType], undefined>,
  'updateCustomer' : ActorMethod<[bigint, Customer], undefined>,
  'updateOrder' : ActorMethod<[bigint, Order], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];