/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CardType {
  'id' : bigint,
  'turnaroundDays' : bigint,
  'name' : string,
  'pricePerCard' : number,
  'description' : string,
}
export interface ClientOrder {
  'id' : bigint,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'cardLayoutChoice' : string,
  'institutionName' : string,
  'institutionType' : string,
  'city' : string,
  'createdAt' : bigint,
  'contactPerson' : string,
  'designImageKey' : [] | [string],
  'canEdit' : boolean,
  'schoolLogoKey' : [] | [string],
  'website' : string,
  'clientPrincipal' : Principal,
  'updatedAt' : bigint,
  'state' : string,
  'colorPreferences' : string,
  'contactEmail' : string,
  'pinCode' : string,
  'cardQuantity' : bigint,
  'contactPhone' : string,
}
export interface Customer {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface DashboardStats {
  'cancelledOrders' : bigint,
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'readyOrders' : bigint,
  'inProductionOrders' : bigint,
  'totalRevenue' : number,
  'deliveredOrders' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'status' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'cardTypeId' : bigint,
  'notes' : string,
  'quantity' : bigint,
  'customerId' : bigint,
  'totalPrice' : number,
}
export type OrderStatus = { 'submitted' : null } |
  { 'printing' : null } |
  { 'designing' : null } |
  { 'dispatched' : null } |
  { 'inReview' : null } |
  { 'delivered' : null };
export type PersonRole = { 'staff' : null } |
  { 'student' : null };
export interface StudentRecord {
  'id' : bigint,
  'parentsContactNumber' : string,
  'dateOfBirth' : string,
  'role' : PersonRole,
  'photoKey' : [] | [string],
  'personName' : string,
  'fathersName' : string,
  'orderId' : bigint,
  'bloodGroup' : string,
  'address' : string,
  'department' : string,
  'classGrade' : string,
  'uploadedAt' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudentRecord' : ActorMethod<[StudentRecord], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkAddStudentRecords' : ActorMethod<[bigint, Array<StudentRecord>], bigint>,
  'createCardType' : ActorMethod<[CardType], bigint>,
  'createClientOrder' : ActorMethod<[ClientOrder], bigint>,
  'createCustomer' : ActorMethod<[Customer], bigint>,
  'createOrder' : ActorMethod<[Order], bigint>,
  'deleteCardType' : ActorMethod<[bigint], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteFile' : ActorMethod<[string], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'deleteStudentRecord' : ActorMethod<[bigint], undefined>,
  'getAllCardTypes' : ActorMethod<[], Array<CardType>>,
  'getAllClientOrders' : ActorMethod<[], Array<ClientOrder>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllFiles' : ActorMethod<[], Array<[string, ExternalBlob]>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCardType' : ActorMethod<[bigint], [] | [CardType]>,
  'getClientOrder' : ActorMethod<[bigint], [] | [ClientOrder]>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyClientOrders' : ActorMethod<[], Array<ClientOrder>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByCustomerId' : ActorMethod<[bigint], Array<Order>>,
  'getOrdersByStatus' : ActorMethod<[string], Array<Order>>,
  'getStudentRecordsByOrder' : ActorMethod<[bigint], Array<StudentRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeClientOrderDesign' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setClientOrderEditPermission' : ActorMethod<[bigint, boolean], undefined>,
  'updateCardType' : ActorMethod<[bigint, CardType], undefined>,
  'updateClientOrder' : ActorMethod<[bigint, ClientOrder], undefined>,
  'updateClientOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateCustomer' : ActorMethod<[bigint, Customer], undefined>,
  'updateOrder' : ActorMethod<[bigint, Order], undefined>,
  'updateStudentRecord' : ActorMethod<[bigint, StudentRecord], undefined>,
  'uploadClientOrderDesign' : ActorMethod<[bigint, string], undefined>,
  'uploadFile' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];