/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CardType = IDL.Record({
  'id' : IDL.Nat,
  'turnaroundDays' : IDL.Nat,
  'name' : IDL.Text,
  'pricePerCard' : IDL.Float64,
  'description' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'cardTypeId' : IDL.Nat,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'customerId' : IDL.Nat,
  'totalPrice' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'cancelledOrders' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'readyOrders' : IDL.Nat,
  'inProductionOrders' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
  'deliveredOrders' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCardType' : IDL.Func([CardType], [IDL.Nat], []),
  'createCustomer' : IDL.Func([Customer], [IDL.Nat], []),
  'createOrder' : IDL.Func([Order], [IDL.Nat], []),
  'deleteCardType' : IDL.Func([IDL.Nat], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'getAllCardTypes' : IDL.Func([], [IDL.Vec(CardType)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCardType' : IDL.Func([IDL.Nat], [IDL.Opt(CardType)], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByCustomerId' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getOrdersByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCardType' : IDL.Func([IDL.Nat, CardType], [], []),
  'updateCustomer' : IDL.Func([IDL.Nat, Customer], [], []),
  'updateOrder' : IDL.Func([IDL.Nat, Order], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CardType = IDL.Record({
    'id' : IDL.Nat,
    'turnaroundDays' : IDL.Nat,
    'name' : IDL.Text,
    'pricePerCard' : IDL.Float64,
    'description' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'cardTypeId' : IDL.Nat,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'customerId' : IDL.Nat,
    'totalPrice' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'cancelledOrders' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'readyOrders' : IDL.Nat,
    'inProductionOrders' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
    'deliveredOrders' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCardType' : IDL.Func([CardType], [IDL.Nat], []),
    'createCustomer' : IDL.Func([Customer], [IDL.Nat], []),
    'createOrder' : IDL.Func([Order], [IDL.Nat], []),
    'deleteCardType' : IDL.Func([IDL.Nat], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'getAllCardTypes' : IDL.Func([], [IDL.Vec(CardType)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCardType' : IDL.Func([IDL.Nat], [IDL.Opt(CardType)], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByCustomerId' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getOrdersByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCardType' : IDL.Func([IDL.Nat, CardType], [], []),
    'updateCustomer' : IDL.Func([IDL.Nat, Customer], [], []),
    'updateOrder' : IDL.Func([IDL.Nat, Order], [], []),
  });
};

export const init = ({ IDL }) => { return []; };