/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ClientOrder {
    id: bigint;
    status: OrderStatus;
    deliveryAddress: string;
    cardLayoutChoice: string;
    institutionName: string;
    institutionType: string;
    city: string;
    createdAt: bigint;
    contactPerson: string;
    designImageKey?: string;
    canEdit: boolean;
    schoolLogoKey?: string;
    website: string;
    clientPrincipal: Principal;
    updatedAt: bigint;
    state: string;
    colorPreferences: string;
    contactEmail: string;
    pinCode: string;
    cardQuantity: bigint;
    contactPhone: string;
}
export interface CardType {
    id: bigint;
    turnaroundDays: bigint;
    name: string;
    pricePerCard: number;
    description: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DashboardStats {
    cancelledOrders: bigint;
    totalOrders: bigint;
    pendingOrders: bigint;
    readyOrders: bigint;
    inProductionOrders: bigint;
    totalRevenue: number;
    deliveredOrders: bigint;
}
export interface Customer {
    id: bigint;
    name: string;
    createdAt: bigint;
    email: string;
    address: string;
    phone: string;
}
export interface Order {
    id: bigint;
    status: string;
    createdAt: bigint;
    updatedAt: bigint;
    cardTypeId: bigint;
    notes: string;
    quantity: bigint;
    customerId: bigint;
    totalPrice: number;
}
export interface StudentRecord {
    id: bigint;
    parentsContactNumber: string;
    dateOfBirth: string;
    role: PersonRole;
    photoKey?: string;
    personName: string;
    fathersName: string;
    orderId: bigint;
    bloodGroup: string;
    address: string;
    department: string;
    classGrade: string;
    uploadedAt: bigint;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum OrderStatus {
    submitted = "submitted",
    printing = "printing",
    designing = "designing",
    dispatched = "dispatched",
    inReview = "inReview",
    delivered = "delivered"
}
export enum PersonRole {
    staff = "staff",
    student = "student"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addStudentRecord(record: StudentRecord): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkAddStudentRecords(orderId: bigint, records: Array<StudentRecord>): Promise<bigint>;
    createCardType(cardType: CardType): Promise<bigint>;
    createClientOrder(clientOrder: ClientOrder): Promise<bigint>;
    createCustomer(customer: Customer): Promise<bigint>;
    createOrder(order: Order): Promise<bigint>;
    deleteCardType(id: bigint): Promise<void>;
    deleteCustomer(id: bigint): Promise<void>;
    deleteFile(id: string): Promise<void>;
    deleteOrder(id: bigint): Promise<void>;
    deleteStudentRecord(id: bigint): Promise<void>;
    getAllCardTypes(): Promise<Array<CardType>>;
    getAllClientOrders(): Promise<Array<ClientOrder>>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllFiles(): Promise<Array<[string, ExternalBlob]>>;
    getAllOrders(): Promise<Array<Order>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCardType(id: bigint): Promise<CardType | null>;
    getClientOrder(id: bigint): Promise<ClientOrder | null>;
    getCustomer(id: bigint): Promise<Customer | null>;
    getDashboardStats(): Promise<DashboardStats>;
    getMyClientOrders(): Promise<Array<ClientOrder>>;
    getOrder(id: bigint): Promise<Order | null>;
    getOrdersByCustomerId(customerId: bigint): Promise<Array<Order>>;
    getOrdersByStatus(status: string): Promise<Array<Order>>;
    getStudentRecordsByOrder(orderId: bigint): Promise<Array<StudentRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeClientOrderDesign(orderId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setClientOrderEditPermission(id: bigint, canEdit: boolean): Promise<void>;
    updateCardType(id: bigint, cardType: CardType): Promise<void>;
    updateClientOrder(id: bigint, updatedOrder: ClientOrder): Promise<void>;
    updateClientOrderStatus(id: bigint, status: OrderStatus): Promise<void>;
    updateCustomer(id: bigint, customer: Customer): Promise<void>;
    updateOrder(id: bigint, order: Order): Promise<void>;
    updateStudentRecord(id: bigint, record: StudentRecord): Promise<void>;
    uploadClientOrderDesign(orderId: bigint, designImageKey: string): Promise<void>;
    uploadFile(id: string, externalBlob: ExternalBlob): Promise<void>;
}
import type { CardType as _CardType, ClientOrder as _ClientOrder, Customer as _Customer, ExternalBlob as _ExternalBlob, Order as _Order, OrderStatus as _OrderStatus, PersonRole as _PersonRole, StudentRecord as _StudentRecord, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addStudentRecord(arg0: StudentRecord): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudentRecord(to_candid_StudentRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudentRecord(to_candid_StudentRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkAddStudentRecords(arg0: bigint, arg1: Array<StudentRecord>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAddStudentRecords(arg0, to_candid_vec_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAddStudentRecords(arg0, to_candid_vec_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCardType(arg0: CardType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCardType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCardType(arg0);
            return result;
        }
    }
    async createClientOrder(arg0: ClientOrder): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClientOrder(to_candid_ClientOrder_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClientOrder(to_candid_ClientOrder_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCustomer(arg0: Customer): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0);
            return result;
        }
    }
    async createOrder(arg0: Order): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0);
            return result;
        }
    }
    async deleteCardType(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCardType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCardType(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteFile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deleteOrder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async deleteStudentRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudentRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudentRecord(arg0);
            return result;
        }
    }
    async getAllCardTypes(): Promise<Array<CardType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCardTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCardTypes();
            return result;
        }
    }
    async getAllClientOrders(): Promise<Array<ClientOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClientOrders();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClientOrders();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllFiles(): Promise<Array<[string, ExternalBlob]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFiles();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFiles();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCardType(arg0: bigint): Promise<CardType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCardType(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCardType(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientOrder(arg0: bigint): Promise<ClientOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientOrder(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientOrder(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMyClientOrders(): Promise<Array<ClientOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyClientOrders();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyClientOrders();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByCustomerId(arg0: bigint): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByCustomerId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByCustomerId(arg0);
            return result;
        }
    }
    async getOrdersByStatus(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(arg0);
            return result;
        }
    }
    async getStudentRecordsByOrder(arg0: bigint): Promise<Array<StudentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentRecordsByOrder(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentRecordsByOrder(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeClientOrderDesign(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeClientOrderDesign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeClientOrderDesign(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setClientOrderEditPermission(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setClientOrderEditPermission(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setClientOrderEditPermission(arg0, arg1);
            return result;
        }
    }
    async updateCardType(arg0: bigint, arg1: CardType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCardType(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCardType(arg0, arg1);
            return result;
        }
    }
    async updateClientOrder(arg0: bigint, arg1: ClientOrder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClientOrder(arg0, to_candid_ClientOrder_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClientOrder(arg0, to_candid_ClientOrder_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateClientOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClientOrderStatus(arg0, to_candid_OrderStatus_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClientOrderStatus(arg0, to_candid_OrderStatus_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCustomer(arg0: bigint, arg1: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1);
            return result;
        }
    }
    async updateOrder(arg0: bigint, arg1: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(arg0, arg1);
            return result;
        }
    }
    async updateStudentRecord(arg0: bigint, arg1: StudentRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudentRecord(arg0, to_candid_StudentRecord_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudentRecord(arg0, to_candid_StudentRecord_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadClientOrderDesign(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadClientOrderDesign(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadClientOrderDesign(arg0, arg1);
            return result;
        }
    }
    async uploadFile(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(arg0, await to_candid_ExternalBlob_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(arg0, await to_candid_ExternalBlob_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ClientOrder_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientOrder): ClientOrder {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_OrderStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PersonRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PersonRole): PersonRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_StudentRecord_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentRecord): StudentRecord {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CardType]): CardType | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClientOrder]): ClientOrder | null {
    return value.length === 0 ? null : from_candid_ClientOrder_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    deliveryAddress: string;
    cardLayoutChoice: string;
    institutionName: string;
    institutionType: string;
    city: string;
    createdAt: bigint;
    contactPerson: string;
    designImageKey: [] | [string];
    canEdit: boolean;
    schoolLogoKey: [] | [string];
    website: string;
    clientPrincipal: Principal;
    updatedAt: bigint;
    state: string;
    colorPreferences: string;
    contactEmail: string;
    pinCode: string;
    cardQuantity: bigint;
    contactPhone: string;
}): {
    id: bigint;
    status: OrderStatus;
    deliveryAddress: string;
    cardLayoutChoice: string;
    institutionName: string;
    institutionType: string;
    city: string;
    createdAt: bigint;
    contactPerson: string;
    designImageKey?: string;
    canEdit: boolean;
    schoolLogoKey?: string;
    website: string;
    clientPrincipal: Principal;
    updatedAt: bigint;
    state: string;
    colorPreferences: string;
    contactEmail: string;
    pinCode: string;
    cardQuantity: bigint;
    contactPhone: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n22(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        cardLayoutChoice: value.cardLayoutChoice,
        institutionName: value.institutionName,
        institutionType: value.institutionType,
        city: value.city,
        createdAt: value.createdAt,
        contactPerson: value.contactPerson,
        designImageKey: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.designImageKey)),
        canEdit: value.canEdit,
        schoolLogoKey: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.schoolLogoKey)),
        website: value.website,
        clientPrincipal: value.clientPrincipal,
        updatedAt: value.updatedAt,
        state: value.state,
        colorPreferences: value.colorPreferences,
        contactEmail: value.contactEmail,
        pinCode: value.pinCode,
        cardQuantity: value.cardQuantity,
        contactPhone: value.contactPhone
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    parentsContactNumber: string;
    dateOfBirth: string;
    role: _PersonRole;
    photoKey: [] | [string];
    personName: string;
    fathersName: string;
    orderId: bigint;
    bloodGroup: string;
    address: string;
    department: string;
    classGrade: string;
    uploadedAt: bigint;
}): {
    id: bigint;
    parentsContactNumber: string;
    dateOfBirth: string;
    role: PersonRole;
    photoKey?: string;
    personName: string;
    fathersName: string;
    orderId: bigint;
    bloodGroup: string;
    address: string;
    department: string;
    classGrade: string;
    uploadedAt: bigint;
} {
    return {
        id: value.id,
        parentsContactNumber: value.parentsContactNumber,
        dateOfBirth: value.dateOfBirth,
        role: from_candid_PersonRole_n38(_uploadFile, _downloadFile, value.role),
        photoKey: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.photoKey)),
        personName: value.personName,
        fathersName: value.fathersName,
        orderId: value.orderId,
        bloodGroup: value.bloodGroup,
        address: value.address,
        department: value.department,
        classGrade: value.classGrade,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _ExternalBlob]): Promise<[string, ExternalBlob]> {
    return [
        value[0],
        await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    printing: null;
} | {
    designing: null;
} | {
    dispatched: null;
} | {
    inReview: null;
} | {
    delivered: null;
}): OrderStatus {
    return "submitted" in value ? OrderStatus.submitted : "printing" in value ? OrderStatus.printing : "designing" in value ? OrderStatus.designing : "dispatched" in value ? OrderStatus.dispatched : "inReview" in value ? OrderStatus.inReview : "delivered" in value ? OrderStatus.delivered : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    staff: null;
} | {
    student: null;
}): PersonRole {
    return "staff" in value ? PersonRole.staff : "student" in value ? PersonRole.student : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientOrder>): Array<ClientOrder> {
    return value.map((x)=>from_candid_ClientOrder_n20(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _ExternalBlob]>): Promise<Array<[string, ExternalBlob]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n26(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentRecord>): Array<StudentRecord> {
    return value.map((x)=>from_candid_StudentRecord_n36(_uploadFile, _downloadFile, x));
}
function to_candid_ClientOrder_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClientOrder): _ClientOrder {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_OrderStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_PersonRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonRole): _PersonRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_StudentRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentRecord): _StudentRecord {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: OrderStatus;
    deliveryAddress: string;
    cardLayoutChoice: string;
    institutionName: string;
    institutionType: string;
    city: string;
    createdAt: bigint;
    contactPerson: string;
    designImageKey?: string;
    canEdit: boolean;
    schoolLogoKey?: string;
    website: string;
    clientPrincipal: Principal;
    updatedAt: bigint;
    state: string;
    colorPreferences: string;
    contactEmail: string;
    pinCode: string;
    cardQuantity: bigint;
    contactPhone: string;
}): {
    id: bigint;
    status: _OrderStatus;
    deliveryAddress: string;
    cardLayoutChoice: string;
    institutionName: string;
    institutionType: string;
    city: string;
    createdAt: bigint;
    contactPerson: string;
    designImageKey: [] | [string];
    canEdit: boolean;
    schoolLogoKey: [] | [string];
    website: string;
    clientPrincipal: Principal;
    updatedAt: bigint;
    state: string;
    colorPreferences: string;
    contactEmail: string;
    pinCode: string;
    cardQuantity: bigint;
    contactPhone: string;
} {
    return {
        id: value.id,
        status: to_candid_OrderStatus_n17(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        cardLayoutChoice: value.cardLayoutChoice,
        institutionName: value.institutionName,
        institutionType: value.institutionType,
        city: value.city,
        createdAt: value.createdAt,
        contactPerson: value.contactPerson,
        designImageKey: value.designImageKey ? candid_some(value.designImageKey) : candid_none(),
        canEdit: value.canEdit,
        schoolLogoKey: value.schoolLogoKey ? candid_some(value.schoolLogoKey) : candid_none(),
        website: value.website,
        clientPrincipal: value.clientPrincipal,
        updatedAt: value.updatedAt,
        state: value.state,
        colorPreferences: value.colorPreferences,
        contactEmail: value.contactEmail,
        pinCode: value.pinCode,
        cardQuantity: value.cardQuantity,
        contactPhone: value.contactPhone
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    parentsContactNumber: string;
    dateOfBirth: string;
    role: PersonRole;
    photoKey?: string;
    personName: string;
    fathersName: string;
    orderId: bigint;
    bloodGroup: string;
    address: string;
    department: string;
    classGrade: string;
    uploadedAt: bigint;
}): {
    id: bigint;
    parentsContactNumber: string;
    dateOfBirth: string;
    role: _PersonRole;
    photoKey: [] | [string];
    personName: string;
    fathersName: string;
    orderId: bigint;
    bloodGroup: string;
    address: string;
    department: string;
    classGrade: string;
    uploadedAt: bigint;
} {
    return {
        id: value.id,
        parentsContactNumber: value.parentsContactNumber,
        dateOfBirth: value.dateOfBirth,
        role: to_candid_PersonRole_n10(_uploadFile, _downloadFile, value.role),
        photoKey: value.photoKey ? candid_some(value.photoKey) : candid_none(),
        personName: value.personName,
        fathersName: value.fathersName,
        orderId: value.orderId,
        bloodGroup: value.bloodGroup,
        address: value.address,
        department: value.department,
        classGrade: value.classGrade,
        uploadedAt: value.uploadedAt
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PersonRole): {
    staff: null;
} | {
    student: null;
} {
    return value == PersonRole.staff ? {
        staff: null
    } : value == PersonRole.student ? {
        student: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    submitted: null;
} | {
    printing: null;
} | {
    designing: null;
} | {
    dispatched: null;
} | {
    inReview: null;
} | {
    delivered: null;
} {
    return value == OrderStatus.submitted ? {
        submitted: null
    } : value == OrderStatus.printing ? {
        printing: null
    } : value == OrderStatus.designing ? {
        designing: null
    } : value == OrderStatus.dispatched ? {
        dispatched: null
    } : value == OrderStatus.inReview ? {
        inReview: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<StudentRecord>): Array<_StudentRecord> {
    return value.map((x)=>to_candid_StudentRecord_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
